### ISSUE TITLE
Chembl pretrained

### ISSUE THREAD

**Issue by bmiles** [Novartis/pqsar2cpd#1]
@michal-pikusa Is there a pre-trained model on CHEMBL you have released or is that for the community to create?

**Comment by michal-pikusa** [comment]
Hi @bmiles,

we don't provide a pre-trained model, however, you should be able to create one fairly easily.

There's a sample ChEMBL dataset in the pQSAR repository for download:
https://github.com/Novartis/pQSAR/tree/main/sample_data

The compounds file contains SMILES that you can encode with MoLeR (which provides a pretrained ChEMBL encoder/decoder - https://github.com/microsoft/molecule-generation). And the assay data file contains the pIC50 values for different ChEMBL assays that can be used to create a profile for each compound. Having both the molecular encodings, and the profiles, you can train pqsar2cpd as shown in the readme.

Hope that helps.
