### ISSUE TITLE
Unable to view the associated paper

### ISSUE THREAD

**Issue by smturzo** [Novartis/pqsar2cpd#2]
Hi I am unable to view the paper associated with this repo. Can you please share the pdf of the paper that was submitted to biorxiv?

**Comment by michal-pikusa** [comment]
Hi @smturzo.

I'm attaching the .pdf, in case you still can't access the paper
[2021.12.10.472084v1.full.pdf](https://github.com/Novartis/pqsar2cpd/files/15218996/2021.12.10.472084v1.full.pdf)
